import os
import shutil
import glob

env = Environment()
env['CC'] = "clang"


source = glob.glob('./app_ert_rtw/*.c')

for i in range(len(source)):
	print(source[i])
	shutil.copy(str(source[i]), './src')

header = glob.glob('./app_ert_rtw/*.h')
for i in range(len(header)):
	print(header[i])
	shutil.copy(str(header[i]), './include')


source = glob.glob('*.c')

for i in range(len(source)):
	print(source[i])
	shutil.copy(str(source[i]), './src')

header = glob.glob('*.h')
for i in range(len(header)):
	print(header[i])
	shutil.copy(str(header[i]), './include')

source = glob.glob('src/*.c')

print(source)

env.SharedLibrary('./lib/libzs11_ctrl', source, LIBS=['m'], CPPPATH='include')


